/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InteractiveExercise = IDL.Record({
  'question' : IDL.Text,
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const LessonSegment = IDL.Record({
  'content' : IDL.Text,
  'exercise' : IDL.Opt(InteractiveExercise),
});
export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'difficulty' : IDL.Text,
  'segments' : IDL.Vec(LessonSegment),
  'category' : IDL.Text,
  'estimatedTime' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Certificate = IDL.Record({
  'id' : IDL.Nat,
  'completionDate' : Time,
  'user' : IDL.Principal,
  'skill' : IDL.Text,
  'verificationId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const UserProgressView = IDL.Record({
  'xp' : IDL.Nat,
  'streak' : IDL.Nat,
  'lastActiveDay' : Time,
  'badges' : IDL.Vec(IDL.Text),
  'completedLessons' : IDL.Vec(IDL.Nat),
  'currentSegment' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLesson' : IDL.Func([Lesson], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateCertificate' : IDL.Func([IDL.Text], [IDL.Opt(Certificate)], []),
  'getAllLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLessonsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProgress' : IDL.Func([], [IDL.Opt(UserProgressView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProgress' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [], []),
  'verifyCertificate' : IDL.Func([IDL.Text], [IDL.Opt(Certificate)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InteractiveExercise = IDL.Record({
    'question' : IDL.Text,
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const LessonSegment = IDL.Record({
    'content' : IDL.Text,
    'exercise' : IDL.Opt(InteractiveExercise),
  });
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'difficulty' : IDL.Text,
    'segments' : IDL.Vec(LessonSegment),
    'category' : IDL.Text,
    'estimatedTime' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Certificate = IDL.Record({
    'id' : IDL.Nat,
    'completionDate' : Time,
    'user' : IDL.Principal,
    'skill' : IDL.Text,
    'verificationId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const UserProgressView = IDL.Record({
    'xp' : IDL.Nat,
    'streak' : IDL.Nat,
    'lastActiveDay' : Time,
    'badges' : IDL.Vec(IDL.Text),
    'completedLessons' : IDL.Vec(IDL.Nat),
    'currentSegment' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLesson' : IDL.Func([Lesson], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateCertificate' : IDL.Func([IDL.Text], [IDL.Opt(Certificate)], []),
    'getAllLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLessonsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProgress' : IDL.Func([], [IDL.Opt(UserProgressView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProgress' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [], []),
    'verifyCertificate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Certificate)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };