/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Certificate {
  'id' : bigint,
  'completionDate' : Time,
  'user' : Principal,
  'skill' : string,
  'verificationId' : string,
}
export interface InteractiveExercise {
  'question' : string,
  'explanation' : string,
  'correctAnswer' : string,
  'options' : Array<string>,
}
export interface Lesson {
  'id' : bigint,
  'title' : string,
  'difficulty' : string,
  'segments' : Array<LessonSegment>,
  'category' : string,
  'estimatedTime' : bigint,
}
export interface LessonSegment {
  'content' : string,
  'exercise' : [] | [InteractiveExercise],
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export interface UserProgressView {
  'xp' : bigint,
  'streak' : bigint,
  'lastActiveDay' : Time,
  'badges' : Array<string>,
  'completedLessons' : Array<bigint>,
  'currentSegment' : Array<[bigint, bigint]>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLesson' : ActorMethod<[Lesson], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateCertificate' : ActorMethod<[string], [] | [Certificate]>,
  'getAllLessons' : ActorMethod<[], Array<Lesson>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLessonsByCategory' : ActorMethod<[string], Array<Lesson>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProgress' : ActorMethod<[], [] | [UserProgressView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProgress' : ActorMethod<[bigint, bigint, boolean], undefined>,
  'verifyCertificate' : ActorMethod<[string], [] | [Certificate]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];